'use strict'

const initGlobal = ()=>{
  console.log('init global config')

  global.SUPER_USER = 'mothcar@naver.com'

  // *************** Server **************************************
  global.BANK_URL = 'http://49.247.19.95:9090'
  // *************** Local Test **********************************
  // global.BANK_URL = 'http://localhost:9091'

  global.REWARD = {
    signUp: 2000,
    loginPoint: 10,
    createPost: 1000,
  }

  global.JOB_LEVEL = {
    super:            "SUPER",
    president:        "SERVANT",
    vice_president:   'VICE_SERVANT',
    depth_1:          'DEPTH_1_CHIEF',
    depth_2:          'DEPTH_2_CHIEF',
    depth_3:          'DEPTH_3_CHIEF',
  }

  global.JOB_NAME = {
    SUPER:            "신급관리자",
    SERVANT:          "NGO 최고관리자",
    VICE_SERVANT:     'NGO 부관리자',
    DEPTH_1_CHIEF:    '시도정보관리자',
    DEPTH_2_CHIEF:    '구군정보관리자',
    DEPTH_3_CHIEF:    '동정보관리자',
  }

  // POLICESTATION,FIRESTATION,JUMINCENTER,GUCENTER,CITYHALL, 
  global.PUB_TYPE = {
    center:           "CENTER_AGENCY",
    judge:            "JUDICIAL",
  }

  global.RCODE = {
    // default states
    NO_RESULT:              'NO_RESULT',
    OPERATION_SUCCEED:      'OPERATION_SUCCEED',
    OPERATION_FAILED:       'OPERATION_FAILED',

    // for exceptions
    EMAIL_DUPLICATED:       'EMAIL_DUPLICATED',
    EMAIL_NOT_FOUND:        'EMAIL_NOT_FOUND',
    ID_NOT_FOUND:           'ID_NOT_FOUND',
    USER_NOT_FOUND:         'USER_NOT_FOUND',
    PAGE_REQUIRED:          'PAGE_REQUIRED',
    LIMIT_REQUIRED:         'LIMIT_REQUIRED',
    ID_REQUIRED:            'ID_REQUIRED',
    INVALID_PAGE:           'INVALID_PAGE',
    INVALID_LIMIT:          'INVALID_LIMIT',
    INVALID_ID:             'INVALID_ID',
    INVALID_PARAMS:         'INVALID_PARAMS',
    CARD_NUM_DUPLICATED:    'CARD_NUM_DUPLICATED',
    CARD_NUM_NOT_FOUND:     'CARD_NUM_NOT_FOUND',
    IS_DEFAULT_NOT_ALLOWED: 'IS_DEFAULT_NOT_ALLOWED',
    ROLE_NOT_ALLOWED:       'ROLE_NOT_ALLOWED',
    EMAIL_NOT_ALLOWED:      'EMAIL_NOT_ALLOWED',
    PASSWORD_NOT_ALLOWED:   'PASSWORD_NOT_ALLOWED',
    ACCOUNT_NUM_NOT_FOUND:  'ACCOUNT_NUM_NOT_FOUND',
    ACCOUNT_NUM_DUPLICATED: 'ACCOUNT_NUM_DUPLICATED',
    IS_READY_NOT_ALLOWED:   'IS_READY_NOT_ALLOWED',
    IS_SALES_NOT_ALLOWED:   'IS_SALES_NOT_ALLOWED',
    PRODUCT_NOT_FOUND:      'PRODUCT_NOT_FOUND',
    PRODUCT_OWNER_NOT_FOUND:'PRODUCT_OWNER_NOT_FOUND',
    VOICE_ID_NOT_ALLOWED:   'VOICE_ID_NOT_ALLOWED',
    VOICE_ID_NOT_FOUND:     'VOICE_ID_NOT_FOUND',
    EMAIL_DENIED:           'EMAIL_DENIED',
    PRODUCT_ID_NOT_FOUND:   'PRODUCT_ID_NOT_FOUND',
    PURCHASE_ID_NOT_FOUND:  'PURCHASE_ID_NOT_FOUND',
    BUYER_ID_NOT_FOUND:     'BUYER_ID_NOT_FOUND',
    KEYWORD_NOT_FOUND:      'KEYWORD_NOT_FOUND',

    EMAIL_REQUIRED:         'EMAIL_REQUIRED',
    PASSWORD_REQUIRED:      'PASSWORD_REQUIRED',
    NAME_REQUIRED:          'NAME_REQUIRED',
    FIRST_NAME_REQUIRED:    'FIRST_NAME_REQUIRED',
    LAST_NAME_REQUIRED:     'LAST_NAME_REQUIRED',
    PHONE1_NUM_REQUIRED:    'PHONE1_NUM_REQUIRED',
    PHONE2_NUM_REQUIRED:    'PHONE2_NUM_REQUIRED',
    COUNTRY_CODE_REQUIRED:  'COUNTRY_CODE_REQUIRED',
    USER_TYPE_REQUIRED:     'USER_TYPE_REQUIRED',
    ALIAS_REQUIRED:         'ALIAS_REQUIRED',
    CARD_NUM_REQUIRED:      'CARD_NUM_REQUIRED',
    EXPIRES_REQUIRED:       'EXPIRES_REQUIRED',
    FULL_NAME_REQUIRED:     'FULL_NAME_REQUIRED',
    ADDRESS1_REQUIRED:      'ADDRESS1_REQUIRED',
    ADDRESS2_REQUIRED:      'ADDRESS2_REQUIRED',
    CITY_REQUIRED:          'CITY_REQUIRED',
    STATE_REQUIRED:         'STATE_REQUIRED',
    ZIPCODE_REQUIRED:       'ZIPCODE_REQUIRED',
    IS_DEFAULT_REQUIRED:    'IS_DEFAULT_REQUIRED',
    THUMBNAIL_URL_REQUIRED: 'THUMBNAIL_URL_REQUIRED',
    ROLE_REQUIRED:          'ROLE_REQUIRED',
    COMPANY_NAME_REQUIRED:  'COMPANY_NAME_REQUIRED',
    BIZ_LICENSE_NUM_REQUIRED:'BIZ_LICENSE_NUM_REQUIRED',
    BANK_NAME_REQUIRED:     'BANK_NAME_REQUIRED',
    ACCOUNT_NUM_REQUIRED:   'ACCOUNT_NUM_REQUIRED',
    ACCOUNT_TYPE_REQUIRED:  'ACCOUNT_TYPE_REQUIRED',
    ROUTING_NUM_REQUIRED:   'ROUTING_NUM_REQUIRED',
    DESCRIPTION_REQUIRED:   'DESCRIPTION_REQUIRED',
    PRICE_REQUIRED:         'PRICE_REQUIRED',
    CURRENCY_REQUIRED:      'CURRENCY_REQUIRED',
    CREATED_BY_REQUIRED:    'CREATED_BY_REQUIRED',
    MODIFIED_BY_REQUIRED:   'MODIFIED_BY_REQUIRED',
    VVS_ID_REQUIRED:        'VVS_ID_REQUIRED',
    VOICE_ID_REQUIRED:      'VOICE_ID_REQUIRED',
    CATEGORY_REQUIRED:      'CATEGORY_REQUIRED',
    CATEGORY_CODE_REQUIRED: 'CATEGORY_CODE_REQUIRED',
    AGE_REQUIRED:           'AGE_REQUIRED',
    COLOR_CODE_REQUIRED:    'COLOR_CODE_REQUIRED',
    COLOR_POS_REQUIRED:     'COLOR_POS_REQUIRED',
    KEYWORDS_REQUIRED:      'KEYWORDS_REQUIRED',
    GENDER_REQUIRED:        'GENDER_REQUIRED',
    IS_VIRTUALVOICE_REQUIRED:'IS_VIRTUALVOICE_REQUIRED',
    VOICEPARAMETERS_REQUIRED:'VOICEPARAMETERS_REQUIRED',
    PRODUCT_ID_REQUIRED:    'PRODUCT_ID_REQUIRED',
    LANGUAGE_REQUIRED:      'LANGUAGE_REQUIRED',
    IS_READY_REQUIRED:      'IS_READY_REQUIRED',
    IS_SALES_REQUIRED:      'IS_SALES_REQUIRED',
    MEDIA_URL_REQUIRED:     'MEDIA_URL_REQUIRED',
    PREVIEW_SCRIPT_REQUIRED:'PREVIEW_SCRIPT_REQUIRED',
    IMAGE_REQUIRED:         'IMAGE_REQUIRED',
    IMAGE_FIELD_REQUIRED:   'IMAGE_FIELD_REQUIRED',
    LOGIN_PROVIDER_REQUIRED:'LOGIN_PROVIDER_REQUIRED',
    PROVIDER_INFO_REQUIRED: 'PROVIDER_INFO_REQUIRED',
    DELETE_ITEMS_REQUIRED:  'DELETE_ITEMS_REQUIRED',
    FROM_ADDRESS_REQUIRED:  'FROM_ADDRESS_REQUIRED',
    TO_ADDRESS_REQUIRED:    'TO_ADDRESS_REQUIRED',
    CONTENT_REQUIRED:       'CONTENT_REQUIRED',
    SUBJECT_REQUIRED:       'SUBJECT_REQUIRED',
    EMAIL_TO_REQUIRED:      'EMAIL_TO_REQUIRED',
    EMAIL_SUBJECT_REQUIRED: 'EMAIL_SUBJECT_REQUIRED',
    EMAIL_HTML_REQUIRED:    'EMAIL_HTML_REQUIRED',
    PRODUCT_NAME_REQUIRED:  'PRODUCT_NAME_REQUIRED',
    PAY_NAME_REQUIRED:      'PAY_NAME_REQUIRED',
    PAY_TYPE_REQUIRED:      'PAY_TYPE_REQUIRED',
    PAY_PROVIDER_REQUIRED:  'PAY_PROVIDER_REQUIRED',
    PAY_STATE_REQUIRED:     'PAY_STATE_REQUIRED',
    TASK_STATE_REQUIRED:    'TASK_STATE_REQUIRED',
    PURCHASE_ID_REQUIRED:   'PURCHASE_ID_REQUIRED',
    USE_TYPE_REQUIRED:      'USE_TYPE_REQUIRED',
    BUYER_ID_REQUIRED:      'BUYER_ID_REQUIRED',
    TEXT_REQUIRED:          'TEXT_REQUIRED',
    EMAIL_CONFIRM_REQUIRED: 'EMAIL_CONFIRM_REQUIRED',
    POPULAR_REQUIRED:       'POPULAR_REQUIRED',
    RECOMMENDED_REQUIRED:   'RECOMMENDED_REQUIRED',
    AUDIO_FIELD_REQUIRED:   'AUDIO_FIELD_REQUIRED',
    FILE_FIELD_REQUIRED:   'FILE_FIELD_REQUIRED',

    INVALID_EMAIL:          'INVALID_EMAIL',
    INVALID_PASSWORD:       'INVALID_PASSWORD',
    INVALID_NAME:           'INVALID_NAME',
    INVALID_FIRST_NAME:     'INVALID_FIRST_NAME',
    INVALID_LAST_NAME:      'INVALID_LAST_NAME',
    INVALID_PHONE1_NUM:     'INVALID_PHONE1_NUM',
    INVALID_PHONE2_NUM:     'INVALID_PHONE2_NUM',
    INVALID_COUNTRY_CODE:   'INVALID_COUNTRY_CODE',
    INVALID_USER_TYPE:      'INVALID_USER_TYPE',
    INVALID_ALIAS:          'INVALID_ALIAS',
    INVALID_CARD_NUM:       'INVALID_CARD_NUM',
    INVALID_EXPIRES:        'INVALID_EXPIRES',
    INVALID_FULL_NAME:      'INVALID_FULL_NAME',
    INVALID_ADDRESS1:       'INVALID_ADDRESS1',
    INVALID_ADDRESS2:       'INVALID_ADDRESS2',
    INVALID_CITY:           'INVALID_CITY',
    INVALID_STATE:          'INVALID_STATE',
    INVALID_ZIPCODE:        'INVALID_ZIPCODE',
    INVALID_IS_DEFAULT:     'INVALID_IS_DEFAULT',
    INVALID_THUMBNAIL_URL:  'INVALID_THUMBNAIL_URL',
    INVALID_ROLE:           'INVALID_ROLE',
    INVALID_COMPANY_NAME:   'INVALID_COMPANY_NAME',
    INVALID_BIZ_LICENSE_NUM:'INVALID_BIZ_LICENSE_NUM',
    INVALID_BANK_NAME:      'INVALID_BANK_NAME',
    INVALID_ACCOUNT_NUM:    'INVALID_ACCOUNT_NUM',
    INVALID_ACCOUNT_TYPE:   'INVALID_ACCOUNT_TYPE',
    INVALID_ROUTING_NUM:    'INVALID_ROUTING_NUM',
    INVALID_DESCRIPTION:    'INVALID_DESCRIPTION',
    INVALID_PRICE:          'INVALID_PRICE',
    INVALID_CURRENCY:       'INVALID_CURRENCY',
    INVALID_CREATED_BY:     'INVALID_CREATED_BY',
    INVALID_MODIFIED_BY:    'INVALID_MODIFIED_BY',
    INVALID_VVS_ID:         'INVALID_VVS_ID',
    INVALID_VOICE_ID:       'INVALID_VOICE_ID',
    INVALID_CATEGORY:       'INVALID_CATEGORY',
    INVALID_CATEGORY_CODE:  'INVALID_CATEGORY_CODE',
    INVALID_AGE:            'INVALID_AGE',
    INVALID_COLOR_CODE:     'INVALID_COLOR_CODE',
    INVALID_COLOR_POS:      'INVALID_COLOR_POS',
    INVALID_KEYWORDS:       'INVALID_KEYWORDS',
    INVALID_KEYWORD:        'INVALID_KEYWORD',
    INVALID_GENDER:         'INVALID_GENDER',
    INVALID_IS_VIRTUALVOICE:'INVALID_IS_VIRTUALVOICE',
    INVALID_PRODUCT_ID:     'INVALID_PRODUCT_ID',
    INVALID_LANGUAGE:       'INVALID_LANGUAGE',
    INVALID_IS_READY:       'INVALID_IS_READY',
    INVALID_IS_SALES:       'INVALID_IS_SALES',
    INVALID_MEDIA_URL:      'INVALID_MEDIA_URL',
    INVALID_PREVIEW_SCRIPT: 'INVALID_PREVIEW_SCRIPT',
    INVALID_IMAGE_FIELD:    'INVALID_IMAGE_FIELD',
    INVALID_LOGIN_PROVIDER: 'INVALID_LOGIN_PROVIDER',
    INVALID_PROVIDER_INFO:  'INVALID_PROVIDER_INFO',
    INVALID_DELETE_ITEMS:   'INVALID_DELETE_ITEMS',
    INVALID_EMAIL_TO:       'INVALID_EMAIL_TO',
    INVALID_EMAIL_SUBJECT:  'INVALID_EMAIL_SUBJECT',
    INVALID_EMAIL_HTML:     'INVALID_EMAIL_HTML',
    INVALID_PRODUCT_NAME:   'INVALID_PRODUCT_NAME',
    INVALID_PAY_NAME:       'INVALID_PAY_NAME',
    INVALID_PAY_TYPE:       'INVALID_PAY_TYPE',
    INVALID_PAY_PROVIDER:   'INVALID_PAY_PROVIDER',
    INVALID_PAY_STATE:      'INVALID_PAY_STATE',
    INVALID_TASK_STATE:     'INVALID_TASK_STATE',
    INVALID_VOICE_PARAMETERS:'INVALID_VOICE_PARAMETERS',
    INVALID_PURCHASE_ID:    'INVALID_PURCHASE_ID',
    INVALID_USE_TYPE:       'INVALID_USE_TYPE',
    INVALID_BUYER_ID:       'INVALID_BUYER_ID',
    INVALID_TEXT:           'INVALID_TEXT',
    INVALID_POPULAR:        'INVALID_POPULAR',
    INVALID_RECOMMENDED:    'INVALID_RECOMMENDED',
    INVALID_IS_SIGNED_OUT:  'INVALID_IS_SIGNED_OUT',
    INVALID_SIGNED_OUT_AT:  'INVALID_SIGNED_OUT_AT',
    INVALID_IS_DELETED:     'INVALID_IS_DELETED',
    INVALID_DELETED_AT:     'INVALID_DELETED_AT',
    INVALID_AUDIO_FIELD:    'INVALID_AUDIO_FIELD',
    INVALID_FILE_FIELD:     'INVALID_FILE_FIELD',

    // for jwt & auth
    INVALID_USER_INFO:      'INVALID_USER_INFO',
    INVALID_TOKEN:          'INVALID_TOKEN',
    TOKEN_EXPIRED:          'TOKEN_EXPIRED',

    OTP_EXPIRED:            'OTP_EXPIRED',
    INVALID_OTP_CODE:       'INVALID_OTP_CODE',
    INVALID_OTP_TYPE:       'INVALID_OTP_TYPE',
    INVALID_AUTH_LEVEL:     'INVALID_AUTH_LEVEL',
    SERVER_ERROR:           'SERVER_ERROR',
    FILE_UPLOAD_ERROR:      'FILE_UPLOAD_ERROR'
  }

  global.VOICE_COLOR = [
    {code:'#C70800',  cssClass: 'passion',      label: 'Passion / Vitality / Efforts',        keywords:'열정,활력,노력,passion,vitality,efforts'},
    {code:'#FF3100',  cssClass: 'freedom',      label: 'Freedom / Change / Challenge',        keywords:'자유,변화,도전,freedom,change,challenge'},
    {code:'#E8481C',  cssClass: 'wisdom',       label: 'Wisdom / Expression / Achievement',   keywords:'지혜,표현,달성,wisdom,expression,achievement'},
    {code:'#F8E71C',  cssClass: 'knowledge',    label: 'Knowledge / Advance / Hope',          keywords:'지식,발전,희망,knowledge,advance,hope'},
    {code:'#B8D94B',  cssClass: 'observation',  label: 'Observation / Safety / Consideration',keywords:'관찰,안심,배려,observation,safety,consideration'},
    {code:'#4A5928',  cssClass: 'stability',    label: 'Stability / Rest / Growth',           keywords:'안정,휴식,성장,stability,rest,growth'},
    {code:'#045D76',  cssClass: 'balance',      label: 'Balance / Cooperation / Invariable',  keywords:'균형,협조,불변,balance,cooperation,invariable'},
    {code:'#067EF2',  cssClass: 'creation',     label: 'Creation / Independence / Cool',      keywords:'창조,자립,냉정,creation,independence,cool'},
    {code:'#014D97',  cssClass: 'communication',label: 'Communication / Sincerity / Self',    keywords:'소통,성실,자신,communication,sincerity,self'},
    {code:'#0D1A6E',  cssClass: 'plan',         label: 'Plan / Judgment / Cleanup',           keywords:'계획,판단,정리,plan,judgment,cleanup'},
    {code:'#623689',  cssClass: 'trust',        label: 'Trust / Focus / Healing',             keywords:'신뢰,집중,힐링,trust,focus,healing'},
    {code:'#BF3F86',  cssClass: 'adoption',     label: 'Adoption / Criminals / Strong',       keywords:'포용,대범,강함,adoption,criminals,strong'}
  ]

  // product category code
  global.CATEGORY = [
    {
      code:   'SW.',
      label:  'Pure Software',
      subCategories: [
        {code: 'SW.TRANSLATION',  label: 'Translation',   keyword:'software, translation'},
        {code: 'SW.EDUCATION',    label: 'Education',     keyword:'software, education'},
        {code: 'SW.EBOOK',        label: 'E-book',        keyword:'software, e-book, ebook'},
        {code: 'SW.CHATBOT',      label: 'Chatbot',       keyword:'software, chatbot'},
        {code: 'SW.MESSENGER',    label: 'Messenger',     keyword:'software, messenger'},
        {code: 'SW.ETC',          label: 'etc.',          keyword:'software'},
      ]
    },
    {
      code:   'SW_HW.',
      label:  'SW + HW',
      subCategories: [
        {code: 'SW_HW.AI_SPEAKER',            label: 'AI Speaker',            keyword:'software, hardware, ai speaker'},
        {code: 'SW_HW.SMART_PHONE',           label: 'Smart Phone',           keyword:'software, hardware, smart phone'},
        {code: 'SW_HW.COMPUTER',              label: 'Computer',              keyword:'software, hardware, computer'},
        {code: 'SW_HW.WEARABLE_DEVICE',       label: 'Wearable Device',       keyword:'software, hardware, wearable device'},
        {code: 'SW_HW.SMART_CAR_NAVIGATION',  label: 'Smart Car Navigation',  keyword:'software, hardware, smart car navigation'},
        {code: 'SW_HW.CAR_ELECTRONIC_INTERFACE',label: 'Car Electronic Interface',keyword:'software, hardware, car electronic interface'},
        {code: 'SW_HW.SMART_HOME_IOT',        label: 'Smart Home IoT',        keyword:'software, hardware, smart home iot'},
        {code: 'SW_HW.ROBOT',                 label: 'Robot',                 keyword:'software, hardware, robot'},
        {code: 'SW_HW.ATM_CD',                label: 'ATM / CD',              keyword:'software, hardware, atm, cd'},
        {code: 'SW_HW.ETC',                   label: 'etc.',                  keyword:'software, hardware'}
      ]
    },
    {
      code:   'HW_EMBEDDED.',
      label:  'Hardware Embedded',
      subCategories: [
        {code: 'HW_EMBEDDED.CONSTRUCTION',    label: 'Construction',    keyword:'hardware, embedded, construction'},
        {code: 'HW_EMBEDDED.ELECTRONIC_PET',  label: 'Electronic Pet',  keyword:'hardware, embedded, electronic pet'},
        {code: 'HW_EMBEDDED.DRON',            label: 'Dron',            keyword:'hardware, embedded, dron'},
        {code: 'HW_EMBEDDED.TOY',             label: 'Toy',             keyword:'hardware, embedded, toy'},
        {code: 'HW_EMBEDDED.ETC',             label: 'etc.',            keyword:'hardware, embedded'}
      ]
    },
    {
      code:   'ENTERTAINMENT.',
      label:  'Entertainment',
      subCategories: [
        {code: 'ENTERTAINMENT.GAME',          label: 'Game',            keyword:'entertainment, game'},
        {code: 'ENTERTAINMENT.ANIMATION',     label: 'Animation',       keyword:'entertainment, animation'},
        {code: 'ENTERTAINMENT.CONCERT',       label: 'Concert',         keyword:'entertainment, concert'},
        {code: 'ENTERTAINMENT.AR_VR_CONTENTS',label: 'AR/VR Contents',  keyword:'entertainment, ar, vr'},
        {code: 'ENTERTAINMENT.ETC',           label: 'etc.',            keyword:'entertainment'}
      ]
    },
    {
      code:   'BROADCASTING.',
      label:  'Broadcasting',
      subCategories: [
        {code: 'BROADCASTING.MCN',                label: 'MCN',             keyword:'broadcasting, mcn'},
        {code: 'BROADCASTING.BROADCAST',          label: 'Broadcast',       keyword:'broadcasting, broadcast'},
        {code: 'BROADCASTING.CONTENT_CREATING',   label: 'Content Creating',keyword:'broadcasting, content creating'},
        {code: 'BROADCASTING.ADVERTISEMENT',      label: 'Advertisement',   keyword:'broadcasting, advertisement, ads'},
        {code: 'BROADCASTING.HOLOGRAM',           label: 'Hologram',        keyword:'broadcasting, hologram'},
        {code: 'BROADCASTING.PUBLIC_NOTICE_SYSTEM',label: 'Public Notice System',keyword:'broadcasting, public notice system'},
        {code: 'BROADCASTING.INTRA_COMMUNICATION',label: 'Intra-Communication',keyword:'broadcasting, intra communication'},
        {code: 'BROADCASTING.ETC',                label: 'etc.',            keyword:'broadcasting'},
      ]
    },
    {
      code:   'IVR_VMS_CTI.',
      label:  'IVR / VMS / CTI',
      subCategories: [
        {code: 'IVR_VMS_CTI.TELEMARKETING',   label: 'Telemarketing',   keyword:'ivr, vms, cti, telemarketing'},
        {code: 'IVR_VMS_CTI.CRM',             label: 'CRM',   keyword:'ivr, vms, cti, crm'},
        {code: 'IVR_VMS_CTI.ARS',             label: 'ARS',   keyword:'ivr, vms, cti, ars'},
        {code: 'IVR_VMS_CTI.ETC',             label: 'etc.',   keyword:'ivr, vms, cti'}
      ]
    },
    {
      code:   'SERVICE.',
      label:  'Service',
      subCategories: [
        {code: 'SERVICE.TRANSPORTATION',    label: 'Transportation',  keyword:'service, transportation'},
        {code: 'SERVICE.MUSEUM_CURATION',   label: 'Museum Curation', keyword:'service, museum curation'},
        {code: 'SERVICE.TRAVEL_GUIDE',      label: 'Travel Guide',    keyword:'service, travel guide'},
        {code: 'SERVICE.VARIOUS_APPS',      label: 'Various Apps',    keyword:'service, various apps'},
        {code: 'SERVICE.ETC',               label: 'etc.',            keyword:'service'}
      ]
    }
  ]

  global.LOGIN_CODE = {
    EMAIL:    'EMAIL',
    FACEBOOK: 'FACEBOOK',
    GOOGLE:   'GOOGLE'
  }

  global.LOGIN_PROVIDER = [
    {code: LOGIN_CODE.EMAIL},
    {code: LOGIN_CODE.FACEBOOK},
    {code: LOGIN_CODE.GOOGLE}
  ]

  global.GENDER = [
    {code: 'M', label: 'Male'},
    {code: 'F', label: 'Female'},
    {code: 'N', label: 'None'}
  ]

  global.LANGUAGE = [
    {code: 'en',  label: 'English'},
    {code: 'zh',  label: 'China'},
    {code: 'ko',  label: 'Korea'}
  ]

  global.USER_ROLE = [
    {code: 'ADMIN'},
    {code: 'OPERATOR'},
    {code: 'USER'}
  ]

  global.USER_TYPE = [
    {code: 'PROVIDER'},
    {code: 'CUSTOMER'}
  ]

  global.ACCOUNT_TYPE = [
    {code: 'CHECKING'},
    {code: 'SAVING'}
  ]

  global.PAY_TYPE = [
    {code: 'CREDIT_CARD'},
    {code: 'PAYPAL'}
  ]

  global.USE_TYPE = [
    {code: 'EASY_USE'},
    {code: 'API_TRACK'}
  ]

  global.PAY_STATE = [
    {code: 'READY'},
    {code: 'COMPLETED'},
    {code: 'IN_PROGRESS'},
    {code: 'ERROR'}
  ]

  global.TASK_STATE = [
    {code: 'READY'},
    {code: 'COMPLETED'},
    {code: 'IN_PROGRESS'},
    {code: 'ERROR'}
  ]

  global.POPULAR_KEYWORD = [
    {code: '#passion'},
    {code: '#challenge'},
    {code: '#wisdom'},
    {code: '#communication'},
    {code: '#trust'},
    {code: '#AI Speaker'},
    {code: '#E-book'},
    {code: '#Museum Curation'},
    {code: '#Travek Guide'},
    {code: '#Smart Car'}
  ]

  global.RECOMMENDED_KEYWORD = [
    {code: '#passion'},
    {code: '#challenge'},
    {code: '#wisdom'},
    {code: '#communication'},
    {code: '#trust'},
    {code: '#adoption'}
  ]

  global.CURRENCY = [
    {code: 'AED', symbol: "\u062f.\u0625;",   label: "UAE dirham"},
    {code: 'AFN', symbol: "Afs",              label: "Afghan afghani"},
    {code: 'ALL', symbol: "L",                label: "Albanian lek"},
    {code: 'AMD', symbol: "AMD",              label: "Armenian dram"},
    {code: 'ANG', symbol: "NA\u0192",         label: "Netherlands Antillean gulden"},
    {code: 'AOA', symbol: "Kz",               label: "Angolan kwanza"},
    {code: 'ARS', symbol: "$",                label: "Argentine peso"},
    {code: 'AUD', symbol: "$",                label: "Australian dollar"},
    {code: 'AWG', symbol: "\u0192",           label: "Aruban florin"},
    {code: 'AZN', symbol: "AZN",              label: "Azerbaijani manat"},
    {code: 'BAM', symbol: "KM",               label: "Bosnia and Herzegovina konvertibilna marka"},
    {code: 'BBD', symbol: "Bds$",             label: "Barbadian dollar"},
    {code: 'BDT', symbol: "\u09f3",           label: "Bangladeshi taka"},
    {code: 'BGN', symbol: "BGN",              label: "Bulgarian lev"},
    {code: 'BHD', symbol: ".\u062f.\u0628",   label: "Bahraini dinar"},
    {code: 'BIF', symbol: "FBu",              label: "Burundi franc"},
    {code: 'BMD', symbol: "BD$",              label: "Bermudian dollar"},
    {code: 'BND', symbol: "B$",               label: "Brunei dollar"},
    {code: 'BOB', symbol: "Bs.",              label: "Bolivian boliviano"},
    {code: 'BRL', symbol: "R$",               label: "Brazilian real"},
    {code: 'BSD', symbol: "B$",               label: "Bahamian dollar"},
    {code: 'BTN', symbol: "Nu.",              label: "Bhutanese ngultrum"},
    {code: 'BWP', symbol: "P",                label: "Botswana pula"},
    {code: 'BYR', symbol: "Br",               label: "Belarusian ruble"},
    {code: 'BZD', symbol: "BZ$",              label: "Belize dollar"},
    {code: 'CAD', symbol: "$",                label: "Canadian dollar"},
    {code: 'CDF', symbol: "F",                label: "Congolese franc"},
    {code: 'CHF', symbol: "Fr.",              label: "Swiss franc"},
    {code: 'CLP', symbol: "$",                label: "Chilean peso"},
    {code: 'CNY', symbol: "\u00a5",           label: "Chinese/Yuan renminbi"},
    {code: 'COP', symbol: "Col$",             label: "Colombian peso"},
    {code: 'CRC', symbol: "\u20a1",           label: "Costa Rican colon"},
    {code: 'CUC', symbol: "$",                label: "Cuban peso"},
    {code: 'CVE', symbol: "Esc",              label: "Cape Verdean escudo"},
    {code: 'CZK', symbol: "K\u010d",          label: "Czech koruna"},
    {code: 'DJF', symbol: "Fdj",              label: "Djiboutian franc"},
    {code: 'DKK', symbol: "Kr",               label: "Danish krone"},
    {code: 'DOP', symbol: "RD$",              label: "Dominican peso"},
    {code: 'DZD', symbol: "\u062f.\u062c",    label: "Algerian dinar"},
    {code: 'EEK', symbol: "KR",               label: "Estonian kroon"},
    {code: 'EGP', symbol: "\u00a3",           label: "Egyptian pound"},
    {code: 'ERN', symbol: "Nfa",              label: "Eritrean nakfa"},
    {code: 'ETB', symbol: "Br",               label: "Ethiopian birr"},
    {code: 'EUR', symbol: "\u20ac",           label: "European Euro"},
    {code: 'FJD', symbol: "FJ$",              label: "Fijian dollar"},
    {code: 'FKP', symbol: "\u00a3",           label: "Falkland Islands pound"},
    {code: 'GBP', symbol: "\u00a3",           label: "British pound"},
    {code: 'GEL', symbol: "GEL",              label: "Georgian lari"},
    {code: 'GHS', symbol: "GH\u20b5",         label: "Ghanaian cedi"},
    {code: 'GIP', symbol: "\u00a3",           label: "Gibraltar pound"},
    {code: 'GMD', symbol: "D",                label: "Gambian dalasi"},
    {code: 'GNF', symbol: "FG",               label: "Guinean franc"},
    {code: 'GQE', symbol: "CFA",              label: "Central African CFA franc"},
    {code: 'GTQ', symbol: "Q",                label: "Guatemalan quetzal"},
    {code: 'GYD', symbol: "GY$",              label: "Guyanese dollar"},
    {code: 'HKD', symbol: "HK$",              label: "Hong Kong dollar"},
    {code: 'HNL', symbol: "L",                label: "Honduran lempira"},
    {code: 'HRK', symbol: "kn",               label: "Croatian kuna"},
    {code: 'HTG', symbol: "G",                label: "Haitian gourde"},
    {code: 'HUF', symbol: "Ft",               label: "Hungarian forint"},
    {code: 'IDR', symbol: "Rp",               label: "Indonesian rupiah"},
    {code: 'ILS', symbol: "\u20aa",           label: "Israeli new sheqel"},
    {code: 'INR', symbol: "\u20B9",           label: "Indian rupee"},
    {code: 'IQD', symbol: "\u062f.\u0639",    label: "Iraqi dinar"},
    {code: 'IRR', symbol: "IRR",              label: "Iranian rial"},
    {code: 'ISK', symbol: "kr",               label: "Icelandic kr\u00f3na"},
    {code: 'JMD', symbol: "J$",               label: "Jamaican dollar"},
    {code: 'JOD', symbol: "JOD",              label: "Jordanian dinar"},
    {code: 'JPY', symbol: "\u00a5",           label: "Japanese yen"},
    {code: 'KES', symbol: "KSh",              label: "Kenyan shilling"},
    {code: 'KGS', symbol: "\u0441\u043e\u043c",label: "Kyrgyzstani som"},
    {code: 'KHR', symbol: "\u17db",           label: "Cambodian riel"},
    {code: 'KMF', symbol: "KMF",              label: "Comorian franc"},
    {code: 'KPW', symbol: "W",                label: "North Korean won"},
    {code: 'KRW', symbol: "W",                label: "South Korean won"},
    {code: 'KWD', symbol: "KWD",              label: "Kuwaiti dinar"},
    {code: 'KYD', symbol: "KY$",              label: "Cayman Islands dollar"},
    {code: 'KZT', symbol: "T",                label: "Kazakhstani tenge"},
    {code: 'LAK', symbol: "KN",               label: "Lao kip"},
    {code: 'LBP', symbol: "\u00a3",           label: "Lebanese lira"},
    {code: 'LKR', symbol: "Rs",               label: "Sri Lankan rupee"},
    {code: 'LRD', symbol: "L$",               label: "Liberian dollar"},
    {code: 'LSL', symbol: "M",                label: "Lesotho loti"},
    {code: 'LTL', symbol: "Lt",               label: "Lithuanian litas"},
    {code: 'LVL', symbol: "Ls",               label: "Latvian lats"},
    {code: 'LYD', symbol: "LD",               label: "Libyan dinar"},
    {code: 'MAD', symbol: "MAD",              label: "Moroccan dirham"},
    {code: 'MDL', symbol: "MDL",              label: "Moldovan leu"},
    {code: 'MGA', symbol: "FMG",              label: "Malagasy ariary"},
    {code: 'MKD', symbol: "MKD",              label: "Macedonian denar"},
    {code: 'MMK', symbol: "K",                label: "Myanma kyat"},
    {code: 'MNT', symbol: "\u20ae",           label: "Mongolian tugrik"},
    {code: 'MOP', symbol: "P",                label: "Macanese pataca"},
    {code: 'MRO', symbol: "UM",               label: "Mauritanian ouguiya"},
    {code: 'MUR', symbol: "Rs",               label: "Mauritian rupee"},
    {code: 'MVR', symbol: "Rf",               label: "Maldivian rufiyaa"},
    {code: 'MWK', symbol: "MK",               label: "Malawian kwacha"},
    {code: 'MXN', symbol: "$",                label: "Mexican peso"},
    {code: 'MYR', symbol: "RM",               label: "Malaysian ringgit"},
    {code: 'MZM', symbol: "MTn",              label: "Mozambican metical"},
    {code: 'NAD', symbol: "N$",               label: "Namibian dollar"},
    {code: 'NGN', symbol: "\u20a6",           label: "Nigerian naira"},
    {code: 'NIO', symbol: "C$",               label: "Nicaraguan c\u00f3rdoba"},
    {code: 'NOK', symbol: "kr",               label: "Norwegian krone"},
    {code: 'NPR', symbol: "NRs",              label: "Nepalese rupee"},
    {code: 'NZD', symbol: "NZ$",              label: "New Zealand dollar"},
    {code: 'OMR', symbol: "OMR",              label: "Omani rial"},
    {code: 'PAB', symbol: "B./",              label: "Panamanian balboa"},
    {code: 'PEN', symbol: "S/.",              label: "Peruvian nuevo sol"},
    {code: 'PGK', symbol: "K",                label: "Papua New Guinean kina"},
    {code: 'PHP', symbol: "\u20b1",           label: "Philippine peso"},
    {code: 'PKR', symbol: "Rs.",              label: "Pakistani rupee"},
    {code: 'PLN', symbol: "z\u0142",          label: "Polish zloty"},
    {code: 'PYG', symbol: "\u20b2",           label: "Paraguayan guarani"},
    {code: 'QAR', symbol: "QR",               label: "Qatari riyal"},
    {code: 'RON', symbol: "L",                label: "Romanian leu"},
    {code: 'RSD', symbol: "din.",             label: "Serbian dinar"},
    {code: 'RUB', symbol: "R",                label: "Russian ruble"},
    {code: 'SAR', symbol: "SR",               label: "Saudi riyal"},
    {code: 'SBD', symbol: "SI$",              label: "Solomon Islands dollar"},
    {code: 'SCR', symbol: "SR",               label: "Seychellois rupee"},
    {code: 'SDG', symbol: "SDG",              label: "Sudanese pound"},
    {code: 'SEK', symbol: "kr",               label: "Swedish krona"},
    {code: 'SGD', symbol: "S$",               label: "Singapore dollar"},
    {code: 'SHP', symbol: "\u00a3",           label: "Saint Helena pound"},
    {code: 'SLL', symbol: "Le",               label: "Sierra Leonean leone"},
    {code: 'SOS', symbol: "Sh.",              label: "Somali shilling"},
    {code: 'SRD', symbol: "$",                label: "Surinamese dollar"},
    {code: 'SYP', symbol: "LS",               label: "Syrian pound"},
    {code: 'SZL', symbol: "E",                label: "Swazi lilangeni"},
    {code: 'THB', symbol: "\u0e3f",           label: "Thai baht"},
    {code: 'TJS', symbol: "TJS",              label: "Tajikistani somoni"},
    {code: 'TMT', symbol: "m",                label: "Turkmen manat"},
    {code: 'TND', symbol: "DT",               label: "Tunisian dinar"},
    {code: 'TRY', symbol: "TRY",              label: "Turkish new lira"},
    {code: 'TTD', symbol: "TT$",              label: "Trinidad and Tobago dollar"},
    {code: 'TWD', symbol: "NT$",              label: "New Taiwan dollar"},
    {code: 'TZS', symbol: "TZS",              label: "Tanzanian shilling"},
    {code: 'UAH', symbol: "UAH",              label: "Ukrainian hryvnia"},
    {code: 'UGX', symbol: "USh",              label: "Ugandan shilling"},
    {code: 'USD', symbol: "US$",              label: "United States dollar"},
    {code: 'UYU', symbol: "$U",               label: "Uruguayan peso"},
    {code: 'UZS', symbol: "UZS",              label: "Uzbekistani som"},
    {code: 'VEB', symbol: "Bs",               label: "Venezuelan bolivar"},
    {code: 'VND', symbol: "\u20ab",           label: "Vietnamese dong"},
    {code: 'VUV', symbol: "VT",               label: "Vanuatu vatu"},
    {code: 'WST', symbol: "WS$",              label: "Samoan tala"},
    {code: 'XAF', symbol: "CFA",              label: "Central African CFA franc"},
    {code: 'XCD', symbol: "EC$",              label: "East Caribbean dollar"},
    {code: 'XDR', symbol: "SDR",              label: "Special Drawing Rights"},
    {code: 'XOF', symbol: "CFA",              label: "West African CFA franc"},
    {code: 'XPF', symbol: "F",                label: "CFP franc"},
    {code: 'YER', symbol: "YER",              label: "Yemeni rial"},
    {code: 'ZAR', symbol: "R",                label: "South African rand"},
    {code: 'ZMK', symbol: "ZK",               label: "Zambian kwacha"},
    {code: 'ZWR', symbol: "Z$",               label: "Zimbabwean dollar"}
  ]

  global.COUNTRY = [
    {code:'AF', phone_code:'+93',   label:'Afghanistan'},
    {code:'AL', phone_code:'+355',  label:'Albania'},
    {code:'DZ', phone_code:'+213',  label:'Algeria'},
    {code:'AS', phone_code:'+1',    label:'American Samoa'},
    {code:'AD', phone_code:'+376',  label:'Andorra'},
    {code:'AO', phone_code:'+244',  label:'Angola'},
    {code:'AI', phone_code:'+1',    label:'Anguilla'},
    {code:'AG', phone_code:'+1',    label:'Antigua'},
    {code:'AR', phone_code:'+54',   label:'Argentina'},
    {code:'AM', phone_code:'+374',  label:'Armenia'},
    {code:'AW', phone_code:'+297',  label:'Aruba'},
    {code:'AU', phone_code:'+61',   label:'Australia'},
    {code:'AI', phone_code:'+43',   label:'Austria'},
    {code:'AZ', phone_code:'+994',  label:'Azerbaijan'},
    {code:'BH', phone_code:'+973',  label:'Bahrain'},
    {code:'BD', phone_code:'+880',  label:'Bangladesh'},
    {code:'BB', phone_code:'+1',    label:'Barbados'},
    {code:'BY', phone_code:'+375',  label:'Belarus'},
    {code:'BE', phone_code:'+32',   label:'Belgium'},
    {code:'BZ', phone_code:'+501',  label:'Belize'},
    {code:'BJ', phone_code:'+229',  label:'Benin'},
    {code:'BM', phone_code:'+1',    label:'Bermuda'},
    {code:'BT', phone_code:'+975',  label:'Bhutan'},
    {code:'BO', phone_code:'+591',  label:'Bolivia'},
    {code:'BA', phone_code:'+387',  label:'Bosnia and Herzegovina'},
    {code:'BW', phone_code:'+267',  label:'Botswana'},
    {code:'BR', phone_code:'+55',   label:'Brazil'},
    {code:'IO', phone_code:'+246',  label:'British Indian Ocean Territory'},
    {code:'VG', phone_code:'+1',    label:'British Virgin Islands', },
    {code:'BN', phone_code:'+673',  label:'Brunei'},
    {code:'BG', phone_code:'+359',  label:'Bulgaria'},
    {code:'BF', phone_code:'+226',  label:'Burkina Faso'},
    {code:'MM', phone_code:'+95',   label:'Burma Myanmar'},
    {code:'BI', phone_code:'+257',  label:'Burundi'},
    {code:'KH', phone_code:'+855',  label:'Cambodia'},
    {code:'CM', phone_code:'+237',  label:'Cameroon'},
    {code:'CA', phone_code:'+1',    label:'Canada'},
    {code:'CV', phone_code:'+238',  label:'Cape Verde'},
    {code:'KY', phone_code:'+1',    label:'Cayman Islands'},
    {code:'CF', phone_code:'+236',  label:'Central African Republic'},
    {code:'ID', phone_code:'+235',  label:'Chad'},
    {code:'CL', phone_code:'+56',   label:'Chile'},
    {code:'CN', phone_code:'+86',   label:'China'},
    {code:'CO', phone_code:'+57',   label:'Colombia'},
    {code:'KM', phone_code:'+269',  label:'Comoros'},
    {code:'CK', phone_code:'+682',  label:'Cook Islands'},
    {code:'CR', phone_code:'+506',  label:'Costa Rica'},
    {code:'CI', phone_code:'+225',  label:'Côte dIvoire'},
    {code:'HR', phone_code:'+385',  label:'Croatia'},
    {code:'CU', phone_code:'+53',   label:'Cuba'},
    {code:'CY', phone_code:'+357',  label:'Cyprus'},
    {code:'CZ', phone_code:'+420',  label:'Czech Republic'},
    {code:'CD', phone_code:'+243',  label:'Democratic Republic of Congo'},
    {code:'DK', phone_code:'+45',   label:'Denmark'},
    {code:'DJ', phone_code:'+253',  label:'Djibouti'},
    {code:'DM', phone_code:'+1',    label:'Dominica'},
    {code:'DO', phone_code:'+1',    label:'Dominican Republic'},
    {code:'EC', phone_code:'+593',  label:'Ecuador'},
    {code:'EG', phone_code:'+20',   label:'Egypt'},
    {code:'SV', phone_code:'+503',  label:'El Salvador'},
    {code:'GQ', phone_code:'+240',  label:'Equatorial Guinea'},
    {code:'ER', phone_code:'+291',  label:'Eritrea'},
    {code:'EE', phone_code:'+372',  label:'Estonia'},
    {code:'ET', phone_code:'+251',  label:'Ethiopia'},
    {code:'FK', phone_code:'+500',  label:'Falkland Islands'},
    {code:'FO', phone_code:'+298',  label:'Faroe Islands'},
    {code:'FM', phone_code:'+691',  label:'Federated States of Micronesia'},
    {code:'FJ', phone_code:'+679',  label:'Fiji'},
    {code:'FI', phone_code:'+358',  label:'Finland'},
    {code:'FR', phone_code:'+33',   label:'France'},
    {code:'GF', phone_code:'+594',  label:'French Guiana'},
    {code:'PF', phone_code:'+689',  label:'French Polynesia'},
    {code:'GA', phone_code:'+241',  label:'Gabon'},
    {code:'GE', phone_code:'+995',  label:'Georgia'},
    {code:'DE', phone_code:'+49',   label:'Germany'},
    {code:'GH', phone_code:'+233',  label:'Ghana'},
    {code:'GI', phone_code:'+350',  label:'Gibraltar'},
    {code:'GR', phone_code:'+30',   label:'Greece'},
    {code:'GL', phone_code:'+299',  label:'Greenland'},
    {code:'GD', phone_code:'+1',    label:'Grenada'},
    {code:'GP', phone_code:'+590',  label:'Guadeloupe'},
    {code:'GU', phone_code:'+1',    label:'Guam'},
    {code:'GT', phone_code:'+502',  label:'Guatemala'},
    {code:'GN', phone_code:'+224',  label:'Guinea'},
    {code:'GW', phone_code:'+245',  label:'Guinea-Bissau'},
    {code:'GY', phone_code:'+592',  label:'Guyana'},
    {code:'HT', phone_code:'+509',  label:'Haiti'},
    {code:'HN', phone_code:'+504',  label:'Honduras'},
    {code:'HK', phone_code:'+852',  label:'Hong Kong'},
    {code:'HU', phone_code:'+36',   label:'Hungary'},
    {code:'IS', phone_code:'+354',  label:'Iceland'},
    {code:'IN', phone_code:'+91',   label:'India'},
    {code:'ID', phone_code:'+62',   label:'Indonesia'},
    {code:'IR', phone_code:'+98',   label:'Iran'},
    {code:'IQ', phone_code:'+964',  label:'Iraq'},
    {code:'IE', phone_code:'+353',  label:'Ireland'},
    {code:'IL', phone_code:'+972',  label:'Israel'},
    {code:'IT', phone_code:'+39',   label:'Italy'},
    {code:'JM', phone_code:'+1',    label:'Jamaica'},
    {code:'JP', phone_code:'+81',   label:'Japan'},
    {code:'JO', phone_code:'+962',  label:'Jordan'},
    {code:'KZ', phone_code:'+7',    label:'Kazakhstan'},
    {code:'KE', phone_code:'+254',  label:'Kenya'},
    {code:'KI', phone_code:'+686',  label:'Kiribati'},
    {code:'XK', phone_code:'+383',  label:'Kosovo'},
    {code:'KW', phone_code:'+965',  label:'Kuwait'},
    {code:'KG', phone_code:'+996',  label:'Kyrgyzstan'},
    {code:'LA', phone_code:'+856',  label:'Laos'},
    {code:'LV', phone_code:'+371',  label:'Latvia'},
    {code:'LB', phone_code:'+961',  label:'Lebanon'},
    {code:'LS', phone_code:'+266',  label:'Lesotho'},
    {code:'LR', phone_code:'+231',  label:'Liberia'},
    {code:'LY', phone_code:'+218',  label:'Libya'},
    {code:'LI', phone_code:'+423',  label:'Liechtenstein'},
    {code:'LT', phone_code:'+370',  label:'Lithuania'},
    {code:'LU', phone_code:'+352',  label:'Luxembourg'},
    {code:'MO', phone_code:'+853',  label:'Macau'},
    {code:'MK', phone_code:'+389',  label:'Macedonia'},
    {code:'MG', phone_code:'+261',  label:'Madagascar'},
    {code:'MW', phone_code:'+265',  label:'Malawi'},
    {code:'MY', phone_code:'+60',   label:'Malaysia'},
    {code:'MV', phone_code:'+960',  label:'Maldives'},
    {code:'ML', phone_code:'+223',  label:'Mali'},
    {code:'MT', phone_code:'+356',  label:'Malta'},
    {code:'MH', phone_code:'+692',  label:'Marshall Islands'},
    {code:'MQ', phone_code:'+596',  label:'Martinique'},
    {code:'MR', phone_code:'+222',  label:'Mauritania'},
    {code:'MU', phone_code:'+230',  label:'Mauritius'},
    {code:'YT', phone_code:'+262',  label:'Mayotte'},
    {code:'MX', phone_code:'+52',   label:'Mexico'},
    {code:'MD', phone_code:'+373',  label:'Moldova'},
    {code:'MC', phone_code:'+377',  label:'Monaco'},
    {code:'MN', phone_code:'+976',  label:'Mongolia'},
    {code:'ME', phone_code:'+382',  label:'Montenegro'},
    {code:'MS', phone_code:'+1',    label:'Montserrat'},
    {code:'MA', phone_code:'+212',  label:'Morocco'},
    {code:'MZ', phone_code:'+258',  label:'Mozambique'},
    {code:'NA', phone_code:'+264',  label:'Namibia'},
    {code:'NR', phone_code:'+674',  label:'Nauru'},
    {code:'NP', phone_code:'+977',  label:'Nepal'},
    {code:'NL', phone_code:'+31',   label:'Netherlands'},
    {code:'AN', phone_code:'+599',  label:'Netherlands Antilles'},
    {code:'NC', phone_code:'+687',  label:'New Caledonia'},
    {code:'NZ', phone_code:'+64',   label:'New Zealand'},
    {code:'NI', phone_code:'+505',  label:'Nicaragua'},
    {code:'NE', phone_code:'+227',  label:'Niger'},
    {code:'NG', phone_code:'+234',  label:'Nigeria'},
    {code:'NU', phone_code:'+683',  label:'Niue'},
    {code:'NF', phone_code:'+672',  label:'Norfolk Island'},
    {code:'KP', phone_code:'+850',  label:'North Korea'},
    {code:'MP', phone_code:'+1',    label:'Northern Mariana Islands'},
    {code:'NO', phone_code:'+47',   label:'Norway'},
    {code:'OM', phone_code:'+968',  label:'Oman'},
    {code:'PK', phone_code:'+92',   label:'Pakistan'},
    {code:'PW', phone_code:'+680',  label:'Palau'},
    {code:'PS', phone_code:'+970',  label:'Palestine'},
    {code:'PA', phone_code:'+507',  label:'Panama'},
    {code:'PG', phone_code:'+675',  label:'Papua New Guinea'},
    {code:'PY', phone_code:'+595',  label:'Paraguay'},
    {code:'PE', phone_code:'+51',   label:'Peru'},
    {code:'PH', phone_code:'+63',   label:'Philippines'},
    {code:'PL', phone_code:'+48',   label:'Poland'},
    {code:'PT', phone_code:'+351',  label:'Portugal'},
    {code:'PR', phone_code:'+1',    label:'Puerto Rico'},
    {code:'QA', phone_code:'+974',  label:'Qatar'},
    {code:'CG', phone_code:'+242',  label:'Republic of the Congo'},
    {code:'RE', phone_code:'+262',  label:'Réunion'},
    {code:'RO', phone_code:'+40',   label:'Romania'},
    {code:'RU', phone_code:'+7',    label:'Russia'},
    {code:'RW', phone_code:'+250',  label:'Rwanda'},
    {code:'BL', phone_code:'+590',  label:'Saint Barthélemy'},
    {code:'SH', phone_code:'+290',  label:'Saint Helena'},
    {code:'KN', phone_code:'+1',    label:'Saint Kitts and Nevis'},
    {code:'MF', phone_code:'+590',  label:'Saint Martin'},
    {code:'PM', phone_code:'+508',  label:'Saint Pierre and Miquelon'},
    {code:'VC', phone_code:'+1',    label:'Saint Vincent and the Grenadines'},
    {code:'WS', phone_code:'+685',  label:'Samoa'},
    {code:'SM', phone_code:'+378',  label:'San Marino'},
    {code:'ST', phone_code:'+239',  label:'São Tomé and Príncipe'},
    {code:'SA', phone_code:'+966',  label:'Saudi Arabia'},
    {code:'SN', phone_code:'+221',  label:'Senegal'},
    {code:'RS', phone_code:'+381',  label:'Serbia'},
    {code:'SC', phone_code:'+248',  label:'Seychelles'},
    {code:'SL', phone_code:'+232',  label:'Sierra Leone'},
    {code:'SG', phone_code:'+65',   label:'Singapore'},
    {code:'SK', phone_code:'+421',  label:'Slovakia'},
    {code:'SI', phone_code:'+386',  label:'Slovenia'},
    {code:'SB', phone_code:'+677',  label:'Solomon Islands'},
    {code:'SO', phone_code:'+252',  label:'Somalia'},
    {code:'ZA', phone_code:'+27',   label:'South Africa'},
    {code:'KR', phone_code:'+82',   label:'South Korea'},
    {code:'ES', phone_code:'+34',   label:'Spain'},
    {code:'LK', phone_code:'+94',   label:'Sri Lanka'},
    {code:'LC', phone_code:'+1',    label:'St. Lucia'},
    {code:'SD', phone_code:'+249',  label:'Sudan'},
    {code:'SR', phone_code:'+597',  label:'Suriname'},
    {code:'SZ', phone_code:'+268',  label:'Swaziland'},
    {code:'SE', phone_code:'+46',   label:'Sweden'},
    {code:'CH', phone_code:'+41',   label:'Switzerland'},
    {code:'SY', phone_code:'+963',  label:'Syria'},
    {code:'TW', phone_code:'+886',  label:'Taiwan'},
    {code:'TJ', phone_code:'+992',  label:'Tajikistan'},
    {code:'TZ', phone_code:'+255',  label:'Tanzania'},
    {code:'TH', phone_code:'+66',   label:'Thailand'},
    {code:'BS', phone_code:'+1',    label:'The Bahamas'},
    {code:'GM', phone_code:'+220',  label:'The Gambia'},
    {code:'TL', phone_code:'+670',  label:'Timor-Leste'},
    {code:'TG', phone_code:'+228',  label:'Togo'},
    {code:'TK', phone_code:'+690',  label:'Tokelau'},
    {code:'TO', phone_code:'+676',  label:'Tonga'},
    {code:'TT', phone_code:'+1',    label:'Trinidad and Tobago'},
    {code:'TN', phone_code:'+216',  label:'Tunisia'},
    {code:'TR', phone_code:'+90',   label:'Turkey'},
    {code:'TM', phone_code:'+993',  label:'Turkmenistan'},
    {code:'TC', phone_code:'+1',    label:'Turks and Caicos Islands'},
    {code:'TV', phone_code:'+688',  label:'Tuvalu'},
    {code:'UG', phone_code:'+256',  label:'Uganda'},
    {code:'UA', phone_code:'+380',  label:'Ukraine'},
    {code:'AE', phone_code:'+971',  label:'United Arab Emirates'},
    {code:'GB', phone_code:'+44',   label:'United Kingdom'},
    {code:'US', phone_code:'+1',    label:'United States'},
    {code:'UY', phone_code:'+598',  label:'Uruguay'},
    {code:'VI', phone_code:'+1',    label:'US Virgin Islands'},
    {code:'UZ', phone_code:'+998',  label:'Uzbekistan'},
    {code:'VU', phone_code:'+678',  label:'Vanuatu'},
    {code:'VA', phone_code:'+39',   label:'Vatican City'},
    {code:'VE', phone_code:'+58',   label:'Venezuela'},
    {code:'VN', phone_code:'+84',   label:'Vietnam'},
    {code:'WF', phone_code:'+681',  label:'Wallis and Futuna'},
    {code:'YE', phone_code:'+967',  label:'Yemen'},
    {code:'ZM', phone_code:'+260',  label:'Zambia'},
    {code:'ZW', phone_code:'+263',  label:'Zimbabwe'}
  ]

  global.TCODE = {
    READY:            'READY',
    COMPLETED:        'COMPLETED',
    ERROR:            'ERROR',
    SPLIT_IN_PROGRESS:'SPLIT_IN_PROGRESS',
    SPLIT_DONE:       'SPLIT_DONE',
    CREATE_IN_PROGRESS:'CREATE_IN_PROGRESS',
    CREATE_DONE:      'CREATE_DONE',
    CONCAT_DONE:      'CONCAT_DONE',
    UPLOAD_IN_PROGRESS:'UPLOAD_IN_PROGRESS',
    UPLOAD_DONE:      'UPLOAD_DONE'
  }

  global.OTP_TYPE = {
    FIND_MY_ID: 'FIND_MY_ID',
    FIND_MY_PW: 'FIND_MY_PW'
  }

  global.AUTH_LEVEL = {
    ADMIN:    'ADMIN',
    OPERATOR: 'OPERATOR',
    USER:     'USER'
  }

  global.PERMISSION = [
    {code: 'PUBLIC'},
    {code: 'PRIVATE'}
  ]

  global.TRAIN_STATE = [
    {code: 'VOICE_UPDATING'},         //
    {code: 'RECORD_FINISHED'},        // 고객이 1시간 녹음을 마친 상태.
    {code: 'USER_REQUEST_TRAINING'},  // 고객이 학습요청을 버튼을 누른 후.
    {code: 'OPERATOR_CONFIRMED'},         // 오퍼레이터가 녹음을 들어본 후, "학습을 해도 좋다"라고 확인함.
    {code: 'TRAINING_IN_PROGRESS'},   // muses.models 에 등록한 voice 상태 이다.
    {code: 'TRAINING_COMPLETED'},     // muses.models 폴링 후, 학습 완료상태를 확인 한 후.
    {code: 'ERROR'}
  ]

  global.MODEL_STATE = [
    {code: 'TRAINING_READY'},         // 새로운 muse.models document 를 생성한 상태
    {code: 'TRAINING_IN_PROGRESS'},   // VVS 가 모델 학습 중인 상태
    {code: 'TRAINING_DONE'},          // VVS 가 모델 학습 마친 상태
    {code: 'ERROR'}                   // 예외 상태
  ]

  global.RESIZE = {
    W:          800,
    H:          600,
    THUMB_W:    200,
    THUMB_H:    200,
    EXT:        '.jpg',
    THUMB_EXT: '.thumb.jpg'
  }

  global.log = console.log.bind(console)
}

module.exports = initGlobal()
